// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXSx2IW0tcz42Z-sg6WjMdBZRfpPRTzwI',
    appId: '1:859370628487:web:93b01c4a499c6d9f9f5f22',
    messagingSenderId: '859370628487',
    projectId: 'chatrooms-6b4a5',
    authDomain: 'chatrooms-6b4a5.firebaseapp.com',
    storageBucket: 'chatrooms-6b4a5.appspot.com',
    measurementId: 'G-JPL5T6VFR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI1D-r0F3DoDvlmQFzrtZJfelFcDmEjuU',
    appId: '1:859370628487:android:e339c18497c00bda9f5f22',
    messagingSenderId: '859370628487',
    projectId: 'chatrooms-6b4a5',
    storageBucket: 'chatrooms-6b4a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAaOGOJYj-m-GHRZJPp9hESH-_3vIh0M',
    appId: '1:859370628487:ios:57a5c7b00989ac979f5f22',
    messagingSenderId: '859370628487',
    projectId: 'chatrooms-6b4a5',
    storageBucket: 'chatrooms-6b4a5.appspot.com',
    iosClientId: '859370628487-taap9pqo21ju3l9n65f7hea1n99rs3v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatrooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvAaOGOJYj-m-GHRZJPp9hESH-_3vIh0M',
    appId: '1:859370628487:ios:57a5c7b00989ac979f5f22',
    messagingSenderId: '859370628487',
    projectId: 'chatrooms-6b4a5',
    storageBucket: 'chatrooms-6b4a5.appspot.com',
    iosClientId: '859370628487-taap9pqo21ju3l9n65f7hea1n99rs3v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatrooms',
  );
}
